name: MetaCleaner Plugin CI

on: [push, pull_request]

jobs:
  code-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pluginbranch: [main, dev]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: plugin

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: intl, soap
          tools: composer

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo "$(cd ci/bin; pwd)" >> $GITHUB_PATH
          echo "$(cd ci/vendor/bin; pwd)" >> $GITHUB_PATH

      - name: Install moodle-plugin-ci
        run: moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1 --branch ${{ matrix.pluginbranch }}

      - name: PHP Lint
        run: moodle-plugin-ci phplint ./plugin

      - name: PHP Mess Detector
        run: moodle-plugin-ci phpmd ./plugin

      - name: Moodle Code Checker (PHPCS)
        run: moodle-plugin-ci phpcs ./plugin

      - name: Check savepoints
        run: moodle-plugin-ci savepoints ./plugin
